name: Build Assets master

env:
  VCPKG_BINARY_SOURCES: "clear;nuget,GitHub,read"
  VCPKG_NUGET_REPOSITORY: "https://github.com/hpcc-systems/vcpkg"

on:
  push:
    tags:
      - "*"

  workflow_dispatch:
    inputs:
      git_ref:
        description: "The git ref to use when checking out the code (e.g. a branch or tag name)"
        required: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: "windows-2019"
            triplet: "x64-windows"
            mono: ""
            sudo: ""
            cmake_config_options: '-G "Visual Studio 16 2019" -T host=x64 -A x64 -DCPACK_THREADS=0 -DCLIENTTOOLS_ONLY=ON -DINCLUDE_PLUGINS=OFF -DUSE_LIBMEMCACHED=OFF -DUSE_CASSANDRA=OFF -DUSE_AZURE=OFF -DWSSQL_SERVICE=OFF'
            cmake_build_options: "--config Release --parallel $NUMBER_OF_PROCESSORS"
          - os: "windows-2022"
            triplet: "x64-windows"
            mono: ""
            sudo: ""
            cmake_config_options: '-G "Visual Studio 17 2022" -T host=x64 -A x64 -DCPACK_THREADS=0 -DCLIENTTOOLS_ONLY=ON -DINCLUDE_PLUGINS=OFF -DUSE_LIBMEMCACHED=OFF -DUSE_CASSANDRA=OFF -DUSE_AZURE=OFF -DWSSQL_SERVICE=OFF'
            cmake_build_options: "--config Release --parallel $NUMBER_OF_PROCESSORS"
          - os: "macos-11"
            triplet: "x64-osx"
            mono: "mono"
            sudo: "sudo"
            cmake_config_options: "-DCMAKE_BUILD_TYPE=Release -DCPACK_THREADS=0 -DCLIENTTOOLS_ONLY=ON -DINCLUDE_PLUGINS=OFF -DUSE_JAVA=OFF"
            cmake_build_options: "--parallel $(nproc)"
          - os: "macos-12"
            triplet: "x64-osx"
            mono: "mono"
            sudo: "sudo"
            cmake_config_options: "-DCMAKE_BUILD_TYPE=Release -DCPACK_THREADS=0 -DCLIENTTOOLS_ONLY=ON -DINCLUDE_PLUGINS=OFF -DUSE_JAVA=OFF"
            cmake_build_options: "--parallel $(nproc)"
      fail-fast: false

    name: "Build Client Tools"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo GitHub context
        shell: "bash"
        run: |
          echo "GitHub context variables:"
          echo "${{ toJSON(github) }}"

      - name: Display build summary
        working-directory: .
        shell: "bash"
        run: |
          echo ${{ matrix.os }} ${{ matrix.triplet }}
          echo "Checkout to $Env:GITHUB_WORKSPACE"

      - name: Ubuntu Dependencies
        if: ${{ contains(matrix.os, 'ubuntu') }}
        shell: "bash"
        run: |
          sudo apt-get update -y
          sudo apt-get install -yq --no-install-recommends \echo
          apt-transport-https \
          autoconf \
          autoconf-archive \
          automake \
          autotools-dev \
          binutils-dev \
          bison \
          build-essential \
          ca-certificates \
          curl \
          dirmngr \
          flex \
          git \
          gnupg \
          groff-base \
          libtool \
          pkg-config \
          software-properties-common \
          tar \
          unzip \
          uuid-dev \
          zip

      - name: Ubuntu Mono Dependencies
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        shell: "bash"
        run: |
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
          echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
          sudo apt-get update -y
          sudo apt-get -yq install -f mono-complete

      - name: OSX Dependencies
        if: ${{ contains(matrix.os, 'macos') }}
        shell: "bash"
        run: |
          brew install bison flex pkg-config autoconf autoconf-archive automake libtool cmake openjdk@11

      - name: "Setup NuGet credentials"
        shell: "bash"
        run: |
          ${{ matrix.mono }} `vcpkg fetch nuget | tail -n 1` \
            sources add \
            -source "https://nuget.pkg.github.com/hpcc-systems/index.json" \
            -storepasswordincleartext \
            -name "GitHub" \
            -username "${{ github.actor }}" \
            -password "${{ secrets.GITHUB_TOKEN }}"

      - name: "Remove builtin vcpkg"
        working-directory: .
        shell: "bash"
        run: |
          ${{ matrix.sudo }} rm -rf "$VCPKG_INSTALLATION_ROOT"

      - name: Check out source code (tag)
        uses: actions/checkout@v3
        if: github.event_name == 'tag'
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: Check out source code (workflow_dispatch)
        uses: actions/checkout@v3
        if: github.event_name != 'tag'
        with:
          ref: ${{ github.event.inputs.ref }}
          submodules: recursive

      - name: "vcpkg Bootstrap"
        working-directory: .
        shell: "bash"
        run: |
          ./vcpkg/bootstrap-vcpkg.sh

      - name: "Generate HPCC-Platform Build Files"
        working-directory: .
        shell: "bash"
        run: |
          mkdir build
          cd build
          cmake .. -DUSE_OPTIONAL=OFF ${{ matrix.cmake_config_options }}

      - name: "Remove vcpkg build files"
        working-directory: ./vcpkg
        shell: "bash"
        run: |
          rm -rf ./buildtrees
          rm -rf ./downloads

      - name: "Build HPCC-Platform"
        working-directory: ./build
        shell: "bash"
        run: |
          cmake --build . ${{ matrix.cmake_build_options }}

      - name: "Build HPCC-Platform"
        working-directory: ./build
        shell: "bash"
        run: |
          cmake --build . ${{ matrix.cmake_build_options }}

      - name: Bundle Package
        shell: "bash"
        run: |
          cmake --build . --target package ${{ matrix.cmake_build_options }}

      - name: Attach build artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            /hpcc-dev/HPCC-Platform/build/*.exe
            /hpcc-dev/HPCC-Platform/build/*.msi
            /hpcc-dev/HPCC-Platform/build/*.dmg
            /hpcc-dev/HPCC-Platform/build/*.pkg

  build-docker:
    strategy:
      matrix:
        os:
          [
            "ubuntu-22.04",
            "ubuntu-20.04",
            "ubuntu-18.04",
            "centos-8",
            "centos-7",
          ]
      fail-fast: false

    name: Build Platform
    runs-on: ubuntu-22.04

    steps:
      - name: Echo GitHub context
        run: |
          echo "GitHub context variables:"
          echo "${{ toJSON(github) }}"

      - name: Check out source code (tag)
        uses: actions/checkout@v3
        if: github.event_name == 'tag'
        with:
          ref: ${{ github.ref }}
          submodules: recursive

      - name: Check out source code (workflow_dispatch)
        uses: actions/checkout@v3
        if: github.event_name != 'tag'
        with:
          ref: ${{ github.event.inputs.ref }}
          submodules: recursive

      - name: Calculate vars
        id: vars
        run: |
          echo "branch_name=$(echo ${{ github.ref }} | cut -d'/' -f3)" >> $GITHUB_OUTPUT
          cd vcpkg
          echo "vcpkg_sha_short=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT
          echo "cmake_options=-DCMAKE_BUILD_TYPE=RelWithDebInfo -DVCPKG_FILES_DIR=/hpcc-dev -DCPACK_THREADS=0 -DUSE_OPTIONAL=OFF -DINCLUDE_PLUGINS=ON -DSUPPRESS_REMBED=ON -DSUPPRESS_V8EMBED=ON" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create Build Image
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: dockerfiles/vcpkg/${{ matrix.os}}.dockerfile
          context: dockerfiles/vcpkg
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/build-${{ matrix.os }}:${{ steps.vars.outputs.branch_name }} 
            ${{ secrets.DOCKER_USERNAME }}/build-${{ matrix.os }}:latest
          cache-from: |
            ${{ secrets.DOCKER_USERNAME }}/build-${{ matrix.os }}:${{ steps.vars.outputs.branch_name }} 
            ${{ secrets.DOCKER_USERNAME }}/build-${{ matrix.os }}:latest
          build-args: |
            VCPKG_REF=${{ steps.vars.outputs.vcpkg_sha_short }}
            BUILD_FOLDER=build-${{ matrix.os }}

      - name: Bundle Regular Package
        run: |
          docker run --rm -v "$(pwd)":/hpcc-dev/HPCC-Platform ${{ secrets.DOCKER_USERNAME }}/build-${{ matrix.os }}:${{ steps.vars.outputs.branch_name }} "cmake -S /hpcc-dev/HPCC-Platform -B /hpcc-dev/HPCC-Platform/build ${{ steps.vars.outputs.cmake_options }}"
          docker run --rm -v "$(pwd)":/hpcc-dev/HPCC-Platform ${{ secrets.DOCKER_USERNAME }}/build-${{ matrix.os }}:${{ steps.vars.outputs.branch_name }} "cmake --build /hpcc-dev/HPCC-Platform/build --parallel $(nproc) --target package"

      - name: Bundle Stripped Package
        run: |
          docker run --rm -v "$(pwd)":/hpcc-dev/HPCC-Platform ${{ secrets.DOCKER_USERNAME }}/build-${{ matrix.os }}:${{ steps.vars.outputs.branch_name }} "cmake -S /hpcc-dev/HPCC-Platform -B /hpcc-dev/HPCC-Platform/build ${{ steps.vars.outputs.cmake_options }} -DCPACK_STRIP_FILES=ON"
          docker run --rm -v "$(pwd)":/hpcc-dev/HPCC-Platform ${{ secrets.DOCKER_USERNAME }}/build-${{ matrix.os }}:${{ steps.vars.outputs.branch_name }} "cmake --build /hpcc-dev/HPCC-Platform/build --parallel $(nproc) --target package"

      - name: Bundle containerized packages
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: |
          docker run --rm -v "$(pwd)":/hpcc-dev/HPCC-Platform ${{ secrets.DOCKER_USERNAME }}/build-${{ matrix.os }}:${{ steps.vars.outputs.branch_name }} "cmake -S /hpcc-dev/HPCC-Platform -B /hpcc-dev/HPCC-Platform/build ${{ steps.vars.outputs.cmake_options }} -DCONTAINERIZED=ON"
          docker run --rm -v "$(pwd)":/hpcc-dev/HPCC-Platform ${{ secrets.DOCKER_USERNAME }}/build-${{ matrix.os }}:${{ steps.vars.outputs.branch_name }} "cmake --build /hpcc-dev/HPCC-Platform/build --parallel $(nproc) --target package"

      - name: Bundle containerized stripped packages
        if: ${{ matrix.os == 'ubuntu-22.04' }}
        run: |
          docker run --rm -v "$(pwd)":/hpcc-dev/HPCC-Platform ${{ secrets.DOCKER_USERNAME }}/build-${{ matrix.os }}:${{ steps.vars.outputs.branch_name }} "cmake -S /hpcc-dev/HPCC-Platform -B /hpcc-dev/HPCC-Platform/build ${{ steps.vars.outputs.cmake_options }} -DCONTAINERIZED=ON -DCPACK_STRIP_FILES=ON"
          docker run --rm -v "$(pwd)":/hpcc-dev/HPCC-Platform ${{ secrets.DOCKER_USERNAME }}/build-${{ matrix.os }}:${{ steps.vars.outputs.branch_name }} "cmake --build /hpcc-dev/HPCC-Platform/build --parallel $(nproc) --target package"

      - name: Attach build artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            /hpcc-dev/HPCC-Platform/build/*.deb
            /hpcc-dev/HPCC-Platform/build/*.rpm
