name: Receive PR

# read-only repo token
# no access to secrets
on:
  pull_request:

jobs:
  build-images:
    strategy:
      matrix:
        image: ["ubuntu-22.04"]
      fail-fast: false

    name: "${{ matrix.image }}"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set vars
        id: vars
        run: echo "sha_short=$(git rev-parse --short=8 HEAD)" >> $GITHUB_OUTPUT

      - name: "Build dockerfile"
        shell: "bash"
        run: |
          docker build --progress plain --pull --rm -f "dockerfiles/${{ matrix.image }}.dockerfile" \
              -t hpccbuilds/vcpkg-${{ matrix.image }}:${{ steps.vars.outputs.sha_short }} \
              -t hpccbuilds/vcpkg-${{ matrix.image }}:latest \
              --build-arg GITHUB_ACTOR=${{ github.actor }} \
              --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
              "."

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/

